development:
  adapter: postgresql
  encoding: unicode
  database: laborsight_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: laborsight_test
  pool: 5
  username: laborsight
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: laborsight_production
  pool: 5
  username: laborsight
  password:
